prompt: |
  Answer (feedbacks, proposes, questions and etc) in Russian language.

memory:
  max_rules: 15
  commit: true

stages:
  hotfix:
    prompt: |
      Find problem and fix it.

      Requirements:
      - Ask user about approve plan

      Constraints:
      - Don't implementation without approve from user
      - Don't research before you receive the task from user
    reflect:
      file: code-design.md
