prompt: |
  Answer (feedbacks, proposes, questions:`*.question.json`, AFM plans) in Russian language.
  Any content written to the project files is in English.

memory:
  max_rules: 15
  commit: true

stages:
  prototype-architecture:
    reflect:
      file: architecture.md
  code-design:
    reflect:
      file: code-design.md
      mode: r
  accept-result:
    manual: false

extend:
  build:
    title: "Build implementation"
    after:
      - commit-changes
    timeout: "8h"
    script: python3 -P -m goga.build "$(python3 -m goga history path -f plan.md)"
    after_script: rm -rf .ralphex
