"""generate command handler - scaffold api/ schema files, api.py fixture modules and empty tests/ dirs from specs."""

import json
import logging
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Optional

import click
from datamodel_code_generator import (
    DataModelType,
    DatetimeClassType,
    Formatter,
    InputFileType,
    LiteralType,
    generate,
)

from ...config import Config, SpecEntry, load_config
from ...spec import Endpoint, extract_endpoints, load_spec

logger = logging.getLogger(__name__)

# JSON-Schema draft id stamped on the request-body fragment before model generation.
_JSON_SCHEMA_DRAFT = "http://json-schema.org/draft-07/schema#"

# Ruff invocation options — match the project's pyproject.toml so generated api.py
# modules are aligned the same way as the pybuggy source (line-length 120, py310).
_RUFF_LINE_LENGTH = "120"
_RUFF_TARGET_VERSION = "py310"

# Matches an OpenAPI path parameter "{name}" (name kept verbatim, incl. case).
_PATH_PARAM_RE = re.compile(r"\{([^}]*)\}")


def _find_ruff() -> str:
    """Locate the ruff executable, preferring PATH then the interpreter's venv.

    Args:
        none.

    Returns:
        Absolute path to the ruff executable.

    Raises:
        click.ClickException: If ruff is neither on PATH nor next to the interpreter.
    """
    found = shutil.which("ruff")
    if found:
        return found

    # When run as `.venv/bin/pytest` the venv may not be on PATH; fall back to the
    # ruff installed alongside the running interpreter.
    candidate = Path(sys.executable).parent / "ruff"
    if candidate.exists():
        return str(candidate)

    raise click.ClickException("ruff executable not found; install ruff to generate api.py fixtures")


def _apply_ruff(source: str) -> str:
    """Align a Python source string with ruff: sort imports then format.

    Runs ``ruff check --fix --select I`` (isort-equivalent import ordering) then
    ``ruff format`` (black-equivalent formatting), both via stdin/stdout with the
    project line-length and target version. Deterministic: identical input yields
    identical output — no timestamps or environment-dependent state.

    Args:
        source: Python source text to align.

    Returns:
        ruff-aligned Python source text (trailing newline included).

    Raises:
        click.ClickException: If any ruff invocation fails.
    """
    ruff = _find_ruff()
    options = ["--line-length", _RUFF_LINE_LENGTH, "--target-version", _RUFF_TARGET_VERSION]

    linted = subprocess.run(
        [ruff, "check", "--fix", "--exit-zero", "--select", "I", *options, "-"],
        input=source,
        capture_output=True,
        check=True,
        text=True,
    )
    formatted = subprocess.run(
        [ruff, "format", *options, "-"],
        input=linted.stdout,
        capture_output=True,
        check=True,
        text=True,
    )
    return formatted.stdout


def _strip_generator_header(source: str) -> str:
    """Drop the leading ``# generated by datamodel-codegen`` comment header.

    datamodel-code-generator prepends a two-line comment header even with
    ``disable_timestamp=True``; remove every leading comment/blank line so only the
    imports and model classes remain.

    Args:
        source: Raw module text produced by ``datamodel_code_generator.generate``.

    Returns:
        Module text without the leading comment header.
    """
    lines = source.splitlines()
    index = 0
    while index < len(lines) and (not lines[index].strip() or lines[index].lstrip().startswith("#")):
        index += 1
    return "\n".join(lines[index:]).strip()


def _collect_request_properties(request: dict) -> dict | None:
    """Return sanitized property schemas for model generation, or None to skip models.

    datamodel-code-generator raises on property fragments that are neither a dict
    nor a boolean (e.g. a stray ``int``/``str``/``list``/``None``). Such fragments
    are replaced by the boolean ``True`` schema (JSON-Schema "any type") to preserve
    the never-raise contract of ``render_api_module``. Returns ``None`` when the
    request has no usable properties (no body, or empty/non-dict ``properties``).

    Args:
        request: Resolved JSON-Schema of the request body.

    Returns:
        Mapping of property name to a valid JSON-Schema fragment, or ``None``.
    """
    properties = request.get("properties")
    if not isinstance(properties, dict) or not properties:
        return None
    return {name: sub if isinstance(sub, (dict, bool)) else True for name, sub in properties.items()}


def _render_request_models(request: dict, properties: dict) -> str:
    """Render pydantic model classes for an endpoint request body via datamodel-code-generator.

    Generates a ``Request`` model (plus any nested object/array models) from the
    resolved request-body JSON-Schema, then strips the generator header. No disk
    I/O — the schema is fed as a JSON string and the module text is returned.

    Args:
        request: Resolved JSON-Schema of the request body (may carry ``type``,
            ``required``, and nested object/array schemas).
        properties: Sanitized property schemas (see ``_collect_request_properties``).

    Returns:
        Model-class source text (header-stripped), deterministic for a given schema.
    """
    schema = {**request, "properties": properties, "$schema": _JSON_SCHEMA_DRAFT}
    source = generate(
        snake_case_field=True,
        capitalise_enum_members=True,
        input_=json.dumps(schema),
        input_file_type=InputFileType.JsonSchema,
        disable_future_imports=True,
        disable_timestamp=True,
        class_name="Request",
        output_model_type=DataModelType.PydanticV2BaseModel,
        use_standard_collections=True,
        enum_field_as_literal=LiteralType.All,
        use_union_operator=True,
        output_datetime_class=DatetimeClassType.Datetime,
        formatters=[Formatter.BUILTIN],
    )
    return _strip_generator_header(source)


def _write_package_markers(bottom: Path, top: Path, force: bool) -> None:
    """Write an empty ``__init__.py`` in every directory from ``bottom`` up to (including) ``top``.

    Makes the generated ``api/<name>/<id>/`` tree an importable Python package by dropping an
    empty ``__init__.py`` marker in each directory on the path to the fixture ``api.py``. A marker
    is created when absent; with ``force`` an existing marker is overwritten — mirroring the
    skip/overwrite semantics of the schema and ``api.py`` files so ``--force`` regenerates the
    whole artifact tree uniformly.

    Args:
        bottom: deepest directory on the package path (the per-endpoint ``api`` dir).
        top: top-most directory on the package path (the ``api`` root); must be an ancestor of ``bottom``.
        force: when true, overwrite an existing ``__init__.py``; when false, skip existing markers.

    Raises:
        none.
    """
    current = bottom
    while True:
        init_file = current / "__init__.py"
        if force or not init_file.exists():
            init_file.write_text("", encoding="utf-8")
        if current == top:
            break
        current = current.parent


def _convert_route(path: str) -> str:
    """Convert OpenAPI ``{param}`` path segments to Express-style ``:param``.

    The parameter name and its case are preserved, e.g. ``{orderID}`` -> ``:orderID``.

    Args:
        path: OpenAPI path template with parameters in braces.

    Returns:
        Route string with parameters rewritten to ``:name`` form.
    """
    return _PATH_PARAM_RE.sub(r":\1", path)


def render_api_module(endpoint: Endpoint) -> str:
    """Render the full source text of an ``api.py`` module for a single endpoint.

    Emits text referencing ``goga_tool_pybuggy.api`` without importing it. Builds a
    deterministic module with a pytest fixture and, when the endpoint has a request
    body with properties, a pydantic ``Request`` model (plus any nested models)
    generated by datamodel-code-generator. The request models and the assembled
    module are aligned through ruff (import sorting + formatting), so the returned
    text is already lint/formatted. Identical ``Endpoint`` input always yields
    identical module text.

    Args:
        endpoint: Endpoint to render the ``api.py`` module for.

    Returns:
        Full source text of the ``api.py`` module (trailing newline included).
    """
    # Normalize to lowercase: the contract documents ``method`` as lowercased, and
    # ``endpoint.id`` always lowercases it when appending the ``_<method>`` suffix,
    # so this keeps fixture-name derivation correct regardless of input case.
    method = endpoint.method.lower()

    # 1. Fixture name: <method>_<id with the trailing "_<method>" removed>
    fixture_name = f"{method}_{endpoint.id.removesuffix('_' + method)}"

    # 2. Route: rewrite each {param} as :param (preserve case)
    route = _convert_route(endpoint.path)

    fixture_block = (
        "@pytest.fixture(scope='function')\n"
        f"def {fixture_name}(api: Api) -> Endpoint:\n"
        f"    return Endpoint(api, '{route}', method='{method.upper()}')"
    )

    # 3. Optional request-body models — only when the body declares usable properties
    properties = _collect_request_properties(endpoint.request)

    # 4. Assemble the module sections, then align the whole text with ruff (merges
    #    the pytest/pybuggy.api imports with the model imports and formats it).
    sections: list[str] = ["import pytest", "from goga_tool_pybuggy.api import Endpoint, Api"]
    if properties:
        sections.append(_render_request_models(endpoint.request, properties))
    sections.append(fixture_block)

    return _apply_ruff("\n\n".join(sections))


def _collect_specs(
    specs: dict[str, SpecEntry], endpoint_filter: set[str] | None, cwd: Path
) -> tuple[list[tuple[str, list[Endpoint]]], set[str]]:
    """Phase 1 — parse, extract and filter the selected specs without writing to disk.

    For each spec: load and validate it (``paths`` required), extract endpoints, warn+skip a spec
    with no operations (pre-filter check), and — when ``endpoint_filter`` is set — keep only
    endpoints whose id is in the filter. Returns the per-spec endpoint lists to generate and the
    set of endpoint ids that matched the filter.

    Args:
        specs: selected spec entries (name -> SpecEntry).
        endpoint_filter: optional set of endpoint ids to keep; ``None`` means keep all.
        cwd: working directory used to resolve each spec location.

    Returns:
        ``(to_generate, matched_ids)`` — ``(name, endpoints)`` pairs plus ids matched by the filter.

    Raises:
        click.ClickException: If a spec has no "paths".
    """
    to_generate: list[tuple[str, list[Endpoint]]] = []
    matched_ids: set[str] = set()
    for name, entry in specs.items():
        spec = load_spec(cwd / entry.location)

        # Validate spec has the required structure
        if "paths" not in spec:
            raise click.ClickException(f"spec has no paths: {entry.location}")

        endpoints = extract_endpoints(spec)

        # No endpoints: warn and skip artifact creation for this spec (pre-filter check,
        # so the warning reflects a spec with no operations, not an empty filter result).
        if not endpoints:
            logger.warning(f"no endpoints; skipping artifacts: {name}")
            continue

        # Apply the optional endpoint-id filter
        if endpoint_filter is not None:
            endpoints = [endpoint for endpoint in endpoints if endpoint.id in endpoint_filter]
            matched_ids |= {endpoint.id for endpoint in endpoints}

        to_generate.append((name, endpoints))

    return to_generate, matched_ids


def _write_artifacts(to_generate: list[tuple[str, list[Endpoint]]], force: bool, cwd: Path) -> None:
    """Phase 2 — write response schemas, per-endpoint api.py fixtures, package markers and test dirs.

    Args:
        to_generate: ``(name, endpoints)`` pairs to scaffold.
        force: when false, existing schema/api.py files and ``__init__.py`` markers are skipped
            silently; when true, they are overwritten.
        cwd: working directory under which the ``api/`` and ``tests/`` trees are written.

    Raises:
        none.
    """
    for name, endpoints in to_generate:
        for endpoint in endpoints:
            endpoint_dir = cwd / "api" / name / endpoint.id
            schemas_dir = endpoint_dir / "schemas"
            schemas_dir.mkdir(parents=True, exist_ok=True)

            test_dir = cwd / "tests" / name / endpoint.id
            test_dir.mkdir(parents=True, exist_ok=True)

            # Empty __init__.py markers on every directory of the api.py path
            # (api/, api/<name>/, api/<name>/<id>/) so the fixture tree is an importable package.
            _write_package_markers(endpoint_dir, cwd / "api", force)

            for status_code, schema in endpoint.response.items():
                schema_file = schemas_dir / f"{status_code}.json"
                if schema_file.exists() and not force:
                    continue
                schema_file.write_text(json.dumps(schema, indent=2, ensure_ascii=False), encoding="utf-8")

            # write the per-endpoint api.py fixture module (force semantics match the schemas)
            api_file = endpoint_dir / "api.py"
            if api_file.exists() and not force:
                continue
            api_file.write_text(render_api_module(endpoint), encoding="utf-8")


def run_generate(spec_name: Optional[str], force: bool, endpoint_ids: Optional[list[str]] = None) -> None:
    """Scaffold api/ response-schema files, api.py fixture modules and empty tests/ directories from the spec config.

    Loads the config from the fixed config path and, for each (optionally filtered) spec, parses the
    spec file, extracts endpoints, optionally filters them by id, and writes response schemas, an
    ``api.py`` pytest-fixture module and empty test directories under the current working directory.

    Two phases — collect/validate (no disk writes) then write — so an unknown endpoint id raises
    before any artifact is written.

    Args:
        spec_name: Optional spec filter; when set generate only that spec, otherwise generate all specs.
        force: When false, existing schema and api.py files are skipped silently; when true, overwritten.
        endpoint_ids: Optional endpoint-id filter (as produced by ``build_endpoint_id``); when set,
            generate only endpoints whose id is in the list. ``None`` or empty generates every endpoint
            of the selected specs. Every requested id must match at least one selected spec, otherwise
            no artifacts are written.

    Raises:
        click.ClickException: If spec_name is set but not found in config specs; a selected spec has
            no "paths"; or endpoint_ids contains an id not found in any selected spec.
    """
    # Step 1: Load the config from the fixed path
    config: Config = load_config()

    # Step 2: Validate the optional spec filter
    if spec_name is not None and spec_name not in config.specs:
        raise click.ClickException(f"spec not found: {spec_name}")

    # Step 3: Select specs (all, or only the filtered one)
    specs: dict[str, SpecEntry] = config.specs if spec_name is None else {spec_name: config.specs[spec_name]}

    # Normalize the endpoint-id filter: an empty filter means "no filter" (all endpoints), so a
    # variadic CLI argument passed with no values behaves identically to the unfiltered command.
    endpoint_filter: set[str] | None = set(endpoint_ids) if endpoint_ids else None

    cwd = Path.cwd()

    # Step 4: Phase 1 — parse, extract, filter and collect (no disk writes yet)
    to_generate, matched_ids = _collect_specs(specs, endpoint_filter, cwd)

    # Step 5: Validate the endpoint-id filter — every requested id must match at least one selected spec
    if endpoint_filter is not None:
        missing = sorted(endpoint_filter - matched_ids)
        if missing:
            raise click.ClickException(f"endpoint not found: {', '.join(missing)}")

    # Step 6: Phase 2 — scaffold artifacts for each selected spec/endpoint
    _write_artifacts(to_generate, force, cwd)


@click.command("generate")
@click.option("-s", "--spec", "spec_name", default=None, help="Spec name to generate")
@click.option("-f", "--force", is_flag=True, default=False, help="Overwrite existing schema and api.py files")
@click.argument("endpoint-ids", nargs=-1, default=None)
def generate_cmd(spec_name: Optional[str], force: bool, endpoint_ids: tuple[str, ...]) -> None:
    """Click wrapper for the endpoint generate subcommand.

    Binds --spec/--force and the positional endpoint-ids filter, then delegates to run_generate.
    """
    run_generate(spec_name, force, list(endpoint_ids) if endpoint_ids else None)
